# =============================================================================
# trial-weave cleanup script
# Run from the repo root: C:\Users\Justin\trial-weave
#
# Usage:
#   .\cleanup.ps1            # dry run - shows what would happen
#   .\cleanup.ps1 -Execute   # actually does the work
# =============================================================================

param(
    [switch]$Execute
)

$ErrorActionPreference = "Stop"

# Make sure we're at the repo root
$expectedRoot = "trial-weave"
if ((Split-Path -Leaf (Get-Location)) -ne $expectedRoot) {
    Write-Host "ERROR: Run this script from the $expectedRoot repo root." -ForegroundColor Red
    Write-Host "  Currently in: $(Get-Location)" -ForegroundColor Yellow
    exit 1
}

if (-not $Execute) {
    Write-Host ""
    Write-Host "===== DRY RUN =====" -ForegroundColor Cyan
    Write-Host "No changes will be made. Run with -Execute to actually clean up."
    Write-Host ""
}

# -----------------------------------------------------------------------------
# Helper: remove a path if it exists
# -----------------------------------------------------------------------------
function Remove-IfExists {
    param([string]$Path, [string]$Reason)

    if (Test-Path $Path) {
        Write-Host "[REMOVE] $Path" -ForegroundColor Yellow
        Write-Host "         reason: $Reason" -ForegroundColor DarkGray
        if ($Execute) {
            Remove-Item -Recurse -Force $Path
        }
    } else {
        Write-Host "[SKIP]   $Path (not found)" -ForegroundColor DarkGray
    }
}

# -----------------------------------------------------------------------------
# Helper: git rm --cached if the path is currently tracked
# -----------------------------------------------------------------------------
function Untrack-IfTracked {
    param([string]$Path)

    # check if anything under that path is tracked by git
    $tracked = git ls-files --error-unmatch $Path 2>$null
    if ($LASTEXITCODE -eq 0 -and $tracked) {
        Write-Host "[UNTRACK] $Path" -ForegroundColor Magenta
        if ($Execute) {
            git rm -r --cached --quiet $Path 2>$null
        }
    }
}

Write-Host ""
Write-Host "===== STEP 1: Remove duplicate lib/src folder =====" -ForegroundColor Cyan
Remove-IfExists "src\lib\src" "Old nested structure - replaced by lib/backend, lib/frontend, lib/core"

Write-Host ""
Write-Host "===== STEP 2: Remove desktop platform folders =====" -ForegroundColor Cyan
Write-Host "  (You're shipping iOS + Android + Web. Desktop folders just create churn on every pub get.)"
Remove-IfExists "src\linux"   "Not shipping to Linux desktop"
Remove-IfExists "src\macos"   "Not shipping to macOS desktop"
Remove-IfExists "src\windows" "Not shipping to Windows desktop"

Write-Host ""
Write-Host "===== STEP 3: Remove leftover build artifacts =====" -ForegroundColor Cyan
Remove-IfExists "dist"          "Old web build output, not part of Flutter project"
Remove-IfExists "src\build"     "Flutter build output - regenerated by flutter build"
Remove-IfExists "src\.dart_tool" "Dart tooling cache - regenerated automatically"

Write-Host ""
Write-Host "===== STEP 4: Remove FVM-managed Flutter SDK (keeps .fvmrc) =====" -ForegroundColor Cyan
Remove-IfExists "src\.fvm\flutter_sdk" "Per-machine SDK install - FVM regenerates"
Remove-IfExists "src\.fvm\versions"    "Per-machine SDK install - FVM regenerates"
Remove-IfExists "src\.fvm\release"     "Per-machine FVM artifact"

Write-Host ""
Write-Host "===== STEP 5: Remove generated platform plugin registrants =====" -ForegroundColor Cyan
Write-Host "  (Flutter regenerates these on every pub get / build.)"
$generatedFiles = @(
    "src\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java",
    "src\ios\Runner\GeneratedPluginRegistrant.h",
    "src\ios\Runner\GeneratedPluginRegistrant.m",
    "src\ios\Flutter\ephemeral",
    "src\macos\Flutter\GeneratedPluginRegistrant.swift",
    "src\macos\Flutter\ephemeral"
)
foreach ($f in $generatedFiles) {
    Remove-IfExists $f "Auto-generated by Flutter tooling"
}

Write-Host ""
Write-Host "===== STEP 6: Remove worktree.txt (the snapshot file) =====" -ForegroundColor Cyan
Remove-IfExists "worktree.txt" "Tree snapshot - not needed in repo"

Write-Host ""
Write-Host "===== STEP 7: Untrack files now covered by .gitignore =====" -ForegroundColor Cyan
Write-Host "  (Files currently tracked by git but should be ignored going forward.)"
$toUntrack = @(
    "src\.dart_tool",
    "src\.fvm\flutter_sdk",
    "src\.fvm\versions",
    "src\.fvm\release",
    "src\build",
    "src\linux",
    "src\macos",
    "src\windows",
    "dist",
    "worktree.txt",
    "src\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java",
    "src\ios\Runner\GeneratedPluginRegistrant.h",
    "src\ios\Runner\GeneratedPluginRegistrant.m",
    "src\ios\Flutter\ephemeral",
    "src\macos\Flutter\GeneratedPluginRegistrant.swift",
    "src\macos\Flutter\ephemeral",
    "src\linux\flutter\generated_plugin_registrant.cc",
    "src\linux\flutter\generated_plugin_registrant.h",
    "src\linux\flutter\generated_plugins.cmake",
    "src\windows\flutter\generated_plugin_registrant.cc",
    "src\windows\flutter\generated_plugin_registrant.h",
    "src\windows\flutter\generated_plugins.cmake"
)
foreach ($p in $toUntrack) {
    Untrack-IfTracked $p
}

Write-Host ""
Write-Host "=================================================================" -ForegroundColor Green
if ($Execute) {
    Write-Host "Cleanup complete." -ForegroundColor Green
    Write-Host ""
    Write-Host "NEXT STEPS:" -ForegroundColor Cyan
    Write-Host "  1. Verify nothing important was deleted:"
    Write-Host "     git status"
    Write-Host ""
    Write-Host "  2. Restore your Flutter SDK via FVM (it points to version in .fvmrc):"
    Write-Host "     cd src"
    Write-Host "     fvm install"
    Write-Host "     fvm flutter pub get"
    Write-Host ""
    Write-Host "  3. Commit the cleanup:"
    Write-Host "     git add -A"
    Write-Host "     git commit -m 'chore: clean up tracked build artifacts and unused platforms'"
} else {
    Write-Host "Dry run complete. Re-run with -Execute to apply." -ForegroundColor Yellow
    Write-Host "  .\cleanup.ps1 -Execute"
}
Write-Host "=================================================================" -ForegroundColor Green
